// ignore_for_file: file_names, camel_case_types

import 'package:w3biblioteca/app/classes/marc_bibliografico/campos_de_numeros_e_codigos_02X_09X/numero_do_registro_original_para_arquivo_de_computador/indicadores/class_indicadores_numero_do_registro_original_para_arquivo_de_computador_036_data.dart';
import 'package:w3biblioteca/app/classes/marc_bibliografico/campos_de_numeros_e_codigos_02X_09X/numero_do_registro_original_para_arquivo_de_computador/subcampos/class_subcampos_numero_do_registro_original_para_arquivo_de_computador_036_data.dart';

class ClassNumeroDoRegistroOriginalParaArquivoDeComputador_02X_09X_Data {
  String etiqueta_036;
  ClassIndicadoresNumeroDoRegistroOriginalParaArquivoDeComputador_036_Data indicadores_036;
  ClassSubcamposNumeroDoRegistroOriginalParaArquivoDeComputador_036_data subcampos_036;

  ClassNumeroDoRegistroOriginalParaArquivoDeComputador_02X_09X_Data(
    this.etiqueta_036,
    this.indicadores_036,
    this.subcampos_036,
  );
}
