// ignore_for_file: file_names
export 'package:w3biblioteca/app/classes/marc_bibliografico/edicao_impressao_etc_25X_28X/area_de_dados_especificos/class_area_de_dados_especificos_25X_28X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/edicao_impressao_etc_25X_28X/caracteristicas_do_arquivo_de_computador/class_caracteristicas_do_arquivo_de_computador_25X_28X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/edicao_impressao_etc_25X_28X/dado_matematico_cartografico/class_dado_matematico_cartografico_25X_28X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/edicao_impressao_etc_25X_28X/data_publicacao_planejada/class_data_publicacao_planejada_25X_28X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/edicao_impressao_etc_25X_28X/edicao/class_edicao_25X_28X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/edicao_impressao_etc_25X_28X/endereco/class_endereco_25X_28X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/edicao_impressao_etc_25X_28X/imprenta/class_imprenta_25X_28X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/edicao_impressao_etc_25X_28X/informacao_sobre_material_filatelico/class_informacao_sobre_material_filatelico_25X_28X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/edicao_impressao_etc_25X_28X/pais_da_identidade_produtora/class_pais_da_entidade_produtora_25X_28X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/edicao_impressao_etc_25X_28X/producao_publicacao_distribuicao_e_nota_copyright/class_producao_publicacao_distribuicao_fabricacao_e_nota_de_copyright_25X_28X_data.dart';
