// ignore_for_file: file_names
export 'package:w3biblioteca/app/classes/marc_bibliografico/entrada_secundaria_70X_75X/detalhes_do_sistema_para_arquivos_de_computador/class_detalhes_do_sistema_para_arquivos_de_computador_70X_75X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entrada_secundaria_70X_75X/entidade/class_entidade_70X_75X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entrada_secundaria_70X_75X/evento/class_evento_70X_75X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entrada_secundaria_70X_75X/forma_hierarquica_do_nome_geografico/class_forma_hierarquica_do_nome_geografico_70X_75X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entrada_secundaria_70X_75X/identificacao_taxonomica/class_identificacao_taxonomica_70X_75X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entrada_secundaria_70X_75X/nome_nao_controlado/class_nome_nao_controlado_70X_75X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entrada_secundaria_70X_75X/nome_pessoal/class_nome_pessoal_70X_75X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entrada_secundaria_70X_75X/titulo_relacionado_e_analitico_nao_controlado/class_titulo_relacionado_e_analitico_nao_controlado_70X_75X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entrada_secundaria_70X_75X/titulo_uniforme/class_titulo_uniforme_70X_75X_data.dart';
