// ignore_for_file: file_names

export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_analitica/class_entrada_analitica_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_da_fonte_do_dado/class_entrada_da_fonte_do_dado_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_formato_fisico_adicional/class_entrada_de_formato_fisico_adicional_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_idioma_original/class_entrada_de_idioma_original_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_outra_edicao/class_entrada_de_outra_edicao_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_publico_com/class_entrada_de_publico_com_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_registro_principal/class_entrada_de_registro_principal_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_serie_principal/class_entrada_de_serie_principal_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_subserie/class_entrada_de_subserie_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_suplemento_especial/class_entrada_de_suplemento_especial_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_titulo_anterior/class_entrada_de_titulo_anterior_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_titulo_posterior/class_entrada_de_titulo_posterior_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_traducao/class_entrada_de_traducao_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/entrada_de_unidade_componente/class_entrada_de_unidade_componente_76X_78X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/entradas_de_ligacao_76X_78X/outras_entradas_de_relacoes/class_outras_entradas_de_relacoes_76X_78X_data.dart';
