// ignore_for_file: file_names
export 'package:w3biblioteca/app/classes/marc_bibliografico/colecoes_localizacao_graficos_alternados_841_88X/colecao_da_instituicao/class_colecao_da_instituicao_841_88X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/colecoes_localizacao_graficos_alternados_841_88X/informacao_de_campos_marc_nao_integrados/class_informacao_de_campos_marc_nao_integrados_841_88X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/colecoes_localizacao_graficos_alternados_841_88X/informacao_de_campos_nao_marc/class_informacao_de_campos_nao_marc_841_88X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/colecoes_localizacao_graficos_alternados_841_88X/informacao_sobre_conversao/class_informacao_sobre_conversao_841_88X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/colecoes_localizacao_graficos_alternados_841_88X/informacao_sobre_correspondencia/class_informacao_sobre_correspondencia_841_88X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/colecoes_localizacao_graficos_alternados_841_88X/localizacao/class_localizacao_841_88X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/colecoes_localizacao_graficos_alternados_841_88X/localizacao_e_acesso_eletronico/class_localizacao_e_acesso_eletronico_841_88X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/colecoes_localizacao_graficos_alternados_841_88X/proveniencia_dos_metadados_gerados_pelo_computador/class_proveniencia_dos_metadados_gerados_pelo_computador_841_88X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/colecoes_localizacao_graficos_alternados_841_88X/representacao_grafica_alternada/class_representacao_grafica_alternada_841_88X_data.dart';
