export 'package:w3biblioteca/app/classes/marc_bibliografico/campos_de_controle_00X/campo_fixo_material_adicional_006/arquivo_de_computador/class_arquivo_de_computador_006_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/campos_de_controle_00X/campo_fixo_material_adicional_006/livro/class_livro_006_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/campos_de_controle_00X/campo_fixo_material_adicional_006/mapa/class_mapa_006_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/campos_de_controle_00X/campo_fixo_material_adicional_006/material_misto/class_material_misto_006_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/campos_de_controle_00X/campo_fixo_material_adicional_006/material_visual/class_material_visual_006_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/campos_de_controle_00X/campo_fixo_material_adicional_006/musica/class_musica_006_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/campos_de_controle_00X/campo_fixo_material_adicional_006/recurso_continuo/class_recurso_continuo_006_data.dart';
