// ignore_for_file: file_names
export 'package:w3biblioteca/app/classes/marc_bibliografico/titulo_e_titulo_relacionado_20X_24X/formas_variantes_do_titulo/class_formas_variantes_do_titulo_20X_24X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/titulo_e_titulo_relacionado_20X_24X/titulo_anterior/class_titulo_anterior_20X_24X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/titulo_e_titulo_relacionado_20x_24X/titulo_abreviado/class_titulo_abreviado_20X_24X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/titulo_e_titulo_relacionado_20x_24X/titulo_chave/class_titulo_chave_20X_24X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/titulo_e_titulo_relacionado_20x_24X/titulo_traduzido_pela_instituicao_catalogadora/class_titulo_traduzido_pela_instituicao_catalogadora_20X_24X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/titulo_e_titulo_relacionado_20x_24X/titulo_uniforme/class_titulo_uniforme_20X_24X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/titulo_e_titulo_relacionado_20x_24X/titulo_uniforme_coletivo/class_titulo_uniforme_coletivo_20X_24X_data.dart';
export 'package:w3biblioteca/app/classes/marc_bibliografico/titulo_e_titulo_relacionado_20X_24X/titulo_principal/class_titulo_principal_20X_24X_data.dart';