import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:w3biblioteca/app/modules/email/controllers/configurar_email_controller.dart';
import 'package:w3biblioteca/app/modules/pesquisa_externa/buscas/controllers/buscas_externa_controller.dart';
import 'package:w3biblioteca/app/modules/pesquisa_externa/buscas/reservas_pesquisa_externa_page.dart';
import 'package:w3biblioteca/app/modules/pesquisa_externa/buscas/widgets/livro_card_pesquisa_externa_widget.dart';
import 'package:w3biblioteca/app/modules/pesquisa_externa/buscas/widgets/monografia_tese_dissertacao_card_pesquisa_externa_widget.dart';
import 'package:w3biblioteca/app/modules/pesquisa_externa/buscas/widgets/qtd_registros_buscas_externa.dart';
import 'package:w3biblioteca/app/modules/reservas/controllers/reservas_controller.dart';
import 'package:w3biblioteca/app/shared/widgets/custom_list_view_widget.dart';
import '../../../classes/classes_do_app/class_app_colors.dart';
import '../../../classes/classes_do_app/class_app_estilos_texto.dart';
import '../../../classes/classes_do_app/class_util.dart';
import '../../../shared/widgets/custom_app_bar_widget.dart';
import '../../../shared/widgets/custom_check_box_widget.dart';
import '../../../shared/widgets/custom_elevated_button_widget.dart';
import '../../../shared/widgets/snack_bar_widget.dart';
import '../../buscas/widgets/botao_limpar_pesquisa_widget.dart';
import '../../buscas/widgets/referencia_widget.dart';
import '../../buscas/widgets/search_widget.dart';
import '../../buscas/widgets/tabs/tab_codigo_marc__autoridade_widget.dart';
import '../../buscas/widgets/tabs/tab_codigo_marc_monografia_tese_dissertacao_widget.dart';
import '../../buscas/widgets/tabs/tab_codigo_marc_widget.dart';
import 'widgets/autoridade_card_pesquisa_externa_widget.dart';

class BuscasExternaPage extends StatelessWidget {
  const BuscasExternaPage({super.key});

  @override
  Widget build(BuildContext context) {
    var buscasController = context.watch<BuscasExternaController>();
    var reservasController = context.watch<ReservasController>();
    var emailController = context.watch<ConfigurarEmailController>();

    var size = MediaQuery.of(context).size;
    var clUtil = ClassUtil();
    return Scaffold(
      appBar:CustomAppBarWidget(
        titulo: 'Buscas',
      ),
      body:Form(
        key: buscasController.formKey,
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: size.width * 0.1, vertical: 32.0),
          child: SingleChildScrollView(
            primary: false,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const SizedBox(height: 16.0),
                SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child: Row(
                    children: [
                      SearchWidget(
                        controller: buscasController.pesquisarController,
                      ),
                      const SizedBox(width: 16.0),
                      CustomElevatedButtonWidget(
                        titulo: 'Pesquisar',
                        cor: ClassAppColors.verde,
                        height: 51,
                        icone: Icons.search_rounded,
                        onPressed: () async {
                          if (buscasController.formKey.currentState!.validate()) {
                              if (buscasController.isCheckLivro == false  && buscasController.isCheckAutoridade == false && buscasController.isCheckMonografiaTeseEDissertacao == false) {
                                ScaffoldMessenger.of(context).showSnackBar(SnackBarWidget(cor: ClassAppColors.vermelho, mensagem: 'É necessário informar um tipo de registro.', largura: size.width * 0.37, altura: size.height * 0.45));
                              } 
                              if (buscasController.isCheckLivro) {
                              buscasController.limparListaLivros();
                              await context.read<BuscasExternaController>().getLivroPorNomePesquisaExterna(nome: buscasController.pesquisarController.text.trim()).then((lista) {
                                if(lista.isEmpty){
                                  ScaffoldMessenger.of(context).showSnackBar(SnackBarWidget(cor: ClassAppColors.vermelho, mensagem: 'Nenhum exemplar encontrado.', largura: size.width * 0.37, altura: size.height * 0.45));
                                } 
                              });
                              } else if (buscasController.isCheckMonografiaTeseEDissertacao) {
                              buscasController.limparListaMonografiaTeseEDissertacao();
                              await context.read<BuscasExternaController>().getMonografiaTeseEDissertacaoPorNome(nomeTese: buscasController.pesquisarController.text.trim()).then((lista) {
                                if(lista.isEmpty){
                                  ScaffoldMessenger.of(context).showSnackBar(SnackBarWidget(cor: ClassAppColors.vermelho, mensagem: 'Nenhum registro encontrado.', largura: size.width * 0.37, altura: size.height * 0.45));
                                }
                              });
                              } else if (buscasController.isCheckAutoridade) {
                              buscasController.limparListaAutoridades();
                              await context.read<BuscasExternaController>().getAutoridades(nomeAutoridade: buscasController.pesquisarController.text.trim()).then((lista) {
                                if(lista.isEmpty){
                                  ScaffoldMessenger.of(context).showSnackBar(SnackBarWidget(cor: ClassAppColors.vermelho, mensagem: 'Nenhuma autoridade encontrada.', largura: size.width * 0.37, altura: size.height * 0.45));
                                } 
                            });
                          }}     
                        },
                      ),
                      const SizedBox(width: 8.0),
                      BotaoLimparPesquisaWidget(
                        onPressed: () {
                            buscasController.limparListaAutoridades();
                            buscasController.limparListaLivros();
                            buscasController.limparListaMonografiaTeseEDissertacao();
                            buscasController.pesquisarController.clear();
                            buscasController.qtdRegistros.clear();
                            buscasController.isCheckLivro = false;
                            buscasController.isCheckAutoridade = false;
                            buscasController.isCheckMonografiaTeseEDissertacao = false;
                          },
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 16.0),
                SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child: Row(
                    children: [
                      CustomCheckBoxWidget(
                        value: buscasController.isCheckLivro,
                        onChanged: (_) => context.read<BuscasExternaController>().marcarCheckLivro(),
                      ),
                      const SizedBox(width: 8.0),
                      Text('Livro', style: ClassAppEstilosTexto.preto16w400Montserrat),
                      const SizedBox(width: 8.0),
                      CustomCheckBoxWidget(
                        value: buscasController.isCheckAutoridade,
                        onChanged: (_) => context.read<BuscasExternaController>().marcarCheckAutoridade(),
                      ),
                      const SizedBox(width: 8.0),
                      Text('Autoridade', style: ClassAppEstilosTexto.preto16w400Montserrat),
                      const SizedBox(width: 8.0),
                      CustomCheckBoxWidget(
                        value: buscasController.isCheckMonografiaTeseEDissertacao,
                        onChanged: (_) => context.read<BuscasExternaController>().marcarCheckMonografiaTeseEDissertacao(),
                      ),
                      const SizedBox(width: 8.0),
                      Text('Monografia/Tese/Dissertação', style: ClassAppEstilosTexto.preto16w400Montserrat),
                    ],
                  ),
                ),
                const SizedBox(height: 8.0),
                // CAMPO DE TEXTO PARA LIMITAR A QUANTIDADE DE REGISTROS
                QtdRegistrosBuscasExternaWidget(
                  controller: buscasController,
                ),
                const SizedBox(height: 16.0),
                //LISTA DE LIVROS
                buscasController.isLoading ? const Center(child: CircularProgressIndicator()) : CustomListViewWidget(
                  itemCount: buscasController.lstLivros.length,
                  itemBuilder: (context, index) {
                    return LivroCardPesquisaExternaWidget(
                      codigoAcergo: buscasController.lstLivros[index].acervoDataID.toString(), 
                      exemplarNumero: buscasController.lstLivros[index].exemplarDataID.toString(), 
                      tituloPrincipal: buscasController.lstLivros[index].$a_tituloPrincipal, 
                      nomePessoal: buscasController.lstLivros[index].$a_nomePessoal_100, 
                      numeroISBN: buscasController.lstLivros[index].$a_numeroISBN, 
                      codigoDaAgenciaCatalogadora: buscasController.lstLivros[index].$a_codigoDaAgenciaCatalogadora, 
                      uri: buscasController.lstLivros[index].$u_identificadorUniformeDeRecursoURI, 
                      livroSituacao: buscasController.lstLivros[index].livroSituacao, 
                      livroReservado: buscasController.lstLivros[index].livroReservado, 
                      numeroDeClassificacao: buscasController.lstLivros[index].$a_numeroDeClassificacaoDecimalUniversal,
                      tabMarcLivro: TabCodigoMarcWidget(
                        lider_000:'${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_000)} ${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].tamanhoDoRegistro_00_04, 5)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].statusDoRegistro_05, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].tipoDeRegistro_06, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].nivelBibliografico_07, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].tipodeControle_08, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].esquemaDeCodificacaoDeCaractere_09, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].numeroDeIndicadores_10, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].numeroDeSubcampos_11, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].enderecoDeDados_12_16, 5)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].nivelDeCodificacao_17, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].formaDeCatalogacaoDescritiva_18, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].nivelDeRegistroDeRecurso_19, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].tamanhoDaParteCorrespondenteAoTamanhoDoCampo_20, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].tamanhoDaPosicaoDoCaractereDeInicio_21, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].tamanhoDaParteDefinidaParaImplementacao_22, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].entradaNaoDefinida_23, 1)}',
                        camposDeControle_00x: '${clUtil.getSubCampoDeControle('001', buscasController.lstLivros[index].numeroDeControle_001)} ${clUtil.getSubCampoDeControle('\n003', buscasController.lstLivros[index].codigoAgenciaCatalogadora_003)} ${clUtil.getSubCampoDeControle('\n005', buscasController.lstLivros[index].dataEHoraUltimaAtualizacao_005)}',
                        todosOsMateriais_008: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_008)} ${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].dataDeEntradaDoRegistroNoArquivo_00_05, 6)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].tipodeDataOuStatusDePublicacao_06, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].data1_07_10, 4)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].data2_11_14, 4)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].lugarDePublicacaoProducaoExecucao_15_17, 3)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].ilustracoes_18_21, 4)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].publicoAlvo_22, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].formaDoDocumento_23, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].naturezaDoConteudo_24_27, 4)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].publicacaoGovernamental_28, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].publicacaoDeConferencia_29, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].obraComemorativa_30, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].indice_31, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].indefinido_32, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].formaLiteraria_33, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].biografia_34, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].idiomaDoTextoDoDocumento_35_37, 3)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].registroModificado_38, 1)}${clUtil.getCampoUnicoDados(buscasController.lstLivros[index].fonteDeCatalogacao_39, 1)}',
                        isbn_020: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_020)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_020, buscasController.lstLivros[index].segundoIndicador_020)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_numeroISBN)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_modalidadesDeAquisicao)} ${clUtil.getSubCampoDados('q', buscasController.lstLivros[index].$q_informacaoQualificadora)} ${clUtil.getSubCampoDados('z', buscasController.lstLivros[index].$z_isbnCanceladoOuInvalido)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_020)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_020)}', 
                        fonteDeCatalogacao_040: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_040)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_040, buscasController.lstLivros[index].segundoIndicador_040)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_codigoDaAgenciaCatalogadora)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_idiomaCatalogacao)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_agenciaQueTranscreveuORegistro)} ${clUtil.getSubCampoDados('d', buscasController.lstLivros[index].$d_agenciaQueAlterouORegistro)} ${clUtil.getSubCampoDados('e', buscasController.lstLivros[index].$e_fontesConvencionaisDedescricaoDeDados)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_040)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_040)}', 
                        codigoDoIdioma_041: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_041)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_041, buscasController.lstLivros[index].segundoIndicador_041)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_codigoDoIdiomaDoTexto)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_codigoDoIdiomaDoResumo)} ${clUtil.getSubCampoDados('d', buscasController.lstLivros[index].$d_codigoDoIdiomaDaMusica)} ${clUtil.getSubCampoDados('e', buscasController.lstLivros[index].$e_codigoDoIdiomaDoLibreto)} ${clUtil.getSubCampoDados('f', buscasController.lstLivros[index].$f_codigoDoIdiomaDoSumario)} ${clUtil.getSubCampoDados('g', buscasController.lstLivros[index].$g_codigoDoIdiomaDoMaterialAdicional)} ${clUtil.getSubCampoDados('h', buscasController.lstLivros[index].$h_codigoDoIdiomaDoDocumentoOriginal)} ${clUtil.getSubCampoDados('j', buscasController.lstLivros[index].$j_codigoDoIdiomaDoSubtituloOuLegenda)} ${clUtil.getSubCampoDados('k', buscasController.lstLivros[index].$k_codigoDoIdiomaDaTraducaoIntermediaria)} ${clUtil.getSubCampoDados('m', buscasController.lstLivros[index].$m_codigoDoIdiomaOriginalDoMaterialAdicional)} ${clUtil.getSubCampoDados('n', buscasController.lstLivros[index].$n_codigoDoIdiomaOriginalDoLibreto)} ${clUtil.getSubCampoDados('2', buscasController.lstLivros[index].$2_fonteDoCodigo_041)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_041)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_041)}',
                        codigoDaAreaGeografica_043: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_043)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_043, buscasController.lstLivros[index].segundoIndicador_043)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_codigoAreaGeografica)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_codigoAreaGeograficaLocal)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_codigoISO)} ${clUtil.getSubCampoDados('0', buscasController.lstLivros[index].$0_numeroDeControleDoRegistroDeAutoridade_043)} ${clUtil.getSubCampoDados('2', buscasController.lstLivros[index].$2_fonteDoCodigo_043)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_043)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_043)}',
                        numeroDeClassificacaoDecimalUniversal_080: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_080)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_080, buscasController.lstLivros[index].segundoIndicador_080)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_numeroDeClassificacaoDecimalUniversal)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_numeroDoItem)} ${clUtil.getSubCampoDados('x', buscasController.lstLivros[index].$x_subdivisaoAuxiliarComum)} ${clUtil.getSubCampoDados('0', buscasController.lstLivros[index].$0_numeroDeControleDoRegistroDeAutoridades)} ${clUtil.getSubCampoDados('2', buscasController.lstLivros[index].$2_numeroDeEdicao)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_080)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_080)}', 
                        numeroDeChamadaLocal_090: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_090)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_090, buscasController.lstLivros[index].segundoIndicador_090)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_classificacao)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_numeroDeCutter)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_anoDePublicacao)} ${clUtil.getSubCampoDados('d', buscasController.lstLivros[index].$d_tipoDeObra)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_unidadeCatalogadora)}',
                        nomePessoal_100: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_100)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_100, buscasController.lstLivros[index].segundoIndicador_100)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_nomePessoal_100)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_algarismosRomanosQueSeguemPrenome)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_titulosEOutrasPalavrasAssociadasAoNome_100)} ${clUtil.getSubCampoDados('d', buscasController.lstLivros[index].$d_datasAssociadasAoNome_100)} ${clUtil.getSubCampoDados('e', buscasController.lstLivros[index].$e_termoDeRelacao_100)} ${clUtil.getSubCampoDados('f', buscasController.lstLivros[index].$f_dataDaPublicacaoDoTrabalho_100)} ${clUtil.getSubCampoDados('g', buscasController.lstLivros[index].$g_informacoesAdicionais_100)} ${clUtil.getSubCampoDados('j', buscasController.lstLivros[index].$j_atributoQualificador)} ${clUtil.getSubCampoDados('k', buscasController.lstLivros[index].$k_subcabecalho)} ${clUtil.getSubCampoDados('l', buscasController.lstLivros[index].$l_idiomaDaPublicacao_100)} ${clUtil.getSubCampoDados('n', buscasController.lstLivros[index].$n_numeroDaSecaoDaPublicacao_100)} ${clUtil.getSubCampoDados('p', buscasController.lstLivros[index].$p_nomeDaSecaoDaPublicacao_100)} ${clUtil.getSubCampoDados('q', buscasController.lstLivros[index].$q_formaCompletaDoNome_100)} ${clUtil.getSubCampoDados('t', buscasController.lstLivros[index].$t_tituloDaPublicacao_100)} ${clUtil.getSubCampoDados('u', buscasController.lstLivros[index].$u_afiliacao_100)} ${clUtil.getSubCampoDados('0', buscasController.lstLivros[index].$0_numeroDeControleDoRegistroDeAutoridade_100)} ${clUtil.getSubCampoDados('4', buscasController.lstLivros[index].$4_relacao_100)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_100)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_100)}', 
                        evento_111: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_111)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_111, buscasController.lstLivros[index].segundoIndicador_111)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_nomeDoEventoOuLugar_111)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_localDeRealizacaoDoEvento_111)} ${clUtil.getSubCampoDados('d', buscasController.lstLivros[index].$d_dataRealizacaoDoEvento_111)} ${clUtil.getSubCampoDados('e', buscasController.lstLivros[index].$e_unidadesSubordinadas_111)} ${clUtil.getSubCampoDados('f', buscasController.lstLivros[index].$f_dataDaPublicacaoDoTrabalho_111)} ${clUtil.getSubCampoDados('g', buscasController.lstLivros[index].$g_informacoesAdicionais_111)} ${clUtil.getSubCampoDados('j', buscasController.lstLivros[index].$j_termoDeRelacao_111)} ${clUtil.getSubCampoDados('k', buscasController.lstLivros[index].$k_subcabecalho_111)} ${clUtil.getSubCampoDados('l', buscasController.lstLivros[index].$l_idiomaDaPublicacao_111)} ${clUtil.getSubCampoDados('m', buscasController.lstLivros[index].$n_numeroDaSecaoDoEvento_111)} ${clUtil.getSubCampoDados('p', buscasController.lstLivros[index].$p_nomeDaSecaoDaPublicacao_111)} ${clUtil.getSubCampoDados('q', buscasController.lstLivros[index].$q_nomeDoEventoSequindoONomeDaJurisdicao_111)} ${clUtil.getSubCampoDados('t', buscasController.lstLivros[index].$t_tituloDaPublicacao_111)} ${clUtil.getSubCampoDados('u', buscasController.lstLivros[index].$u_afiliacao_111)} ${clUtil.getSubCampoDados('0', buscasController.lstLivros[index].$0_numeroDeControleDoRegistroDeAutoridade_111)} ${clUtil.getSubCampoDados('4', buscasController.lstLivros[index].$4_relacao_111)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_111)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_111)}',
                        tituloOriginal_240: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_240)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_240, buscasController.lstLivros[index].segundoIndicador_240)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_tituloUniforme)} ${clUtil.getSubCampoDados('d', buscasController.lstLivros[index].$d_dataDaAssinaturaTratado)} ${clUtil.getSubCampoDados('f', buscasController.lstLivros[index].$f_dataDaPublicacaoDoTrabalho_240)} ${clUtil.getSubCampoDados('g', buscasController.lstLivros[index].$g_informacoesAdicionais_240)} ${clUtil.getSubCampoDados('h', buscasController.lstLivros[index].$h_meioDGM_240)} ${clUtil.getSubCampoDados('k', buscasController.lstLivros[index].$k_subcabecalho_240)} ${clUtil.getSubCampoDados('l', buscasController.lstLivros[index].$l_idiomaDaPublicacao_240)} ${clUtil.getSubCampoDados('m', buscasController.lstLivros[index].$m_meioDeExecucaoParaMusica)} ${clUtil.getSubCampoDados('n', buscasController.lstLivros[index].$n_numeroDaSecaoDaPublicacao_240)} ${clUtil.getSubCampoDados('o', buscasController.lstLivros[index].$o_arranjoMusical_240)} ${clUtil.getSubCampoDados('p', buscasController.lstLivros[index].$p_nomeDaSecaoDaPublicacao_240)} ${clUtil.getSubCampoDados('r', buscasController.lstLivros[index].$r_escalaMusical_240)} ${clUtil.getSubCampoDados('s', buscasController.lstLivros[index].$s_versao_240)} ${clUtil.getSubCampoDados('0', buscasController.lstLivros[index].$0_numeroDeControleDoRegistroDeAutoridade_240)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_240)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_240)}',
                        tituloPrincipal_245: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_245)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_245, buscasController.lstLivros[index].segundoIndicador_245)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_tituloPrincipal)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_subtitulo)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_indicacaoDeResponsabilidade)} ${clUtil.getSubCampoDados('f', buscasController.lstLivros[index].$f_datasDeAbrangencia)} ${clUtil.getSubCampoDados('g', buscasController.lstLivros[index].$g_conjuntoDeDatas)} ${clUtil.getSubCampoDados('h', buscasController.lstLivros[index].$h_meioDGM_245)} ${clUtil.getSubCampoDados('k', buscasController.lstLivros[index].$k_formaDoMaterial)} ${clUtil.getSubCampoDados('n', buscasController.lstLivros[index].$n_numeroDaSecaoDaPublicacao_245)} ${clUtil.getSubCampoDados('p', buscasController.lstLivros[index].$p_nomeDaSecaoDaPublicacao_245)} ${clUtil.getSubCampoDados('s', buscasController.lstLivros[index].$s_versao_245)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_245)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_245)}', 
                        edicao_250: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_250)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_250, buscasController.lstLivros[index].segundoIndicador_250)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_edicao)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_outrasInformacoesSobreEdicao)} ${clUtil.getSubCampoDados('3', buscasController.lstLivros[index].$3_materialEspecificado_250)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_250)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumerosDeSequencia_250)}',
                        imprenta_260: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_260)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_260, buscasController.lstLivros[index].segundoIndicador_260)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_lugarDePublicacao)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_nomeDoEditor)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_dataDePublicacao)} ${clUtil.getSubCampoDados('e', buscasController.lstLivros[index].$e_lugarDeFabricacao)} ${clUtil.getSubCampoDados('f', buscasController.lstLivros[index].$f_nomeDoFabricante)} ${clUtil.getSubCampoDados('g', buscasController.lstLivros[index].$g_dataDeFabricacao)} ${clUtil.getSubCampoDados('3', buscasController.lstLivros[index].$3_materialEspecificado_260)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_260)}',
                        descricaoFisica_300: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_300)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_300, buscasController.lstLivros[index].segundoIndicador_300)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_extensao)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_detalhesFisicosAdicionais)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_dimensoes)} ${clUtil.getSubCampoDados('e', buscasController.lstLivros[index].$e_materialAdicional)} ${clUtil.getSubCampoDados('f', buscasController.lstLivros[index].$f_tipoDeUnidade)} ${clUtil.getSubCampoDados('g', buscasController.lstLivros[index].$g_tamanhoDaUnidade)} ${clUtil.getSubCampoDados('3', buscasController.lstLivros[index].$3_materialEspecificado_300)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_300)}',
                        indicacaoDeSerie_490: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_490)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_490, buscasController.lstLivros[index].segundoIndicador_490)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_tituloDaSerie)} ${clUtil.getSubCampoDados('l', buscasController.lstLivros[index].$l_numeroDeChamadaDaLC)} ${clUtil.getSubCampoDados('v', buscasController.lstLivros[index].$v_numeroDoVolumeOuDesignacaoSequencialDaSerie)} ${clUtil.getSubCampoDados('x', buscasController.lstLivros[index].$x_ISSN_490)} ${clUtil.getSubCampoDados('3', buscasController.lstLivros[index].$3_materialEspecificado_490)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_490)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_490)}',
                        notaGeral_500: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_500)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_500, buscasController.lstLivros[index].segundoIndicador_500)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_notaGeral)} ${clUtil.getSubCampoDados('3', buscasController.lstLivros[index].$3_materialEspecificado_500)} ${clUtil.getSubCampoDados('5', buscasController.lstLivros[index].$5_codigoDaInstituicao_500)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_500)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_500)}',
                        notaGeral_500_DataID: buscasController.lstLivros[index].notaGeral_500_DataID.toString(),
                        notaDeBibliografia_504: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_504)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_504, buscasController.lstLivros[index].segundoIndicador_504)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_notaDeBibliografia)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_numeroDeReferencias)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_504)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_504)}',
                        notaDeConteudo_505: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_505)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_505, buscasController.lstLivros[index].segundoIndicador_505)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_notaDeConteudo)} ${clUtil.getSubCampoDados('g', buscasController.lstLivros[index].$g_informacoesAdicionais)} ${clUtil.getSubCampoDados('r', buscasController.lstLivros[index].$r_indicacaoDeResposabilidade)} ${clUtil.getSubCampoDados('t', buscasController.lstLivros[index].$t_titulo)} ${clUtil.getSubCampoDados('u', buscasController.lstLivros[index].$u_URI)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_505)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_505)}',
                        notaDeResumo_520: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_520)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_520, buscasController.lstLivros[index].segundoIndicador_520)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_notaDeResumo)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_expansaoDaNotaDeResumo)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_agenciaDepositaria)} ${clUtil.getSubCampoDados('u', buscasController.lstLivros[index].$u_URI_520)} ${clUtil.getSubCampoDados('2', buscasController.lstLivros[index].$2_fonte_520)} ${clUtil.getSubCampoDados('3', buscasController.lstLivros[index].$3_materialEspecificado_520)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_520)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_520)}',
                        topico_650: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_650)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_650, buscasController.lstLivros[index].segundoIndicador_650)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_cabecalhoTopicoOuNomeGeografico)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_cabecalhoTopicoSeguindoNomeGeografico)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_localDoEvento)} ${clUtil.getSubCampoDados('d', buscasController.lstLivros[index].$d_dataDeRealizacaoDoEvento)} ${clUtil.getSubCampoDados('e', buscasController.lstLivros[index].$e_termoDeRelacao_650)} ${clUtil.getSubCampoDados('g', buscasController.lstLivros[index].$g_informacoesAdicionais_650)} ${clUtil.getSubCampoDados('v', buscasController.lstLivros[index].$v_subdivisaoDeForma)} ${clUtil.getSubCampoDados('x', buscasController.lstLivros[index].$x_subdivisaoGeral)} ${clUtil.getSubCampoDados('y', buscasController.lstLivros[index].$y_subdivisaoCronologica)} ${clUtil.getSubCampoDados('z', buscasController.lstLivros[index].$z_subdivisaoGeografica)} ${clUtil.getSubCampoDados('0', buscasController.lstLivros[index].$0_numeroDeControleDoRegistroDeAutoridade_650)} ${clUtil.getSubCampoDados('2', buscasController.lstLivros[index].$2_fonteDoCabecalhoOuTermo)} ${clUtil.getSubCampoDados('3', buscasController.lstLivros[index].$3_materialEspecificado_650)} ${clUtil.getSubCampoDados('4', buscasController.lstLivros[index].$4_relacao_650)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_650)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_650)}',
                        topico_650_DataID: buscasController.lstLivros[index].topico_650_DataID.toString(),
                        nomePessoalSecundario_700: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_700)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_700, buscasController.lstLivros[index].segundoIndicador_700)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_nomePessoal_700)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_algarismosRomanosQueSeguemOPrenome)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_titulosEOutrasPalavrasAssociadasAoNome_700)} ${clUtil.getSubCampoDados('d', buscasController.lstLivros[index].$d_datasAssociadasAoNome_700)} ${clUtil.getSubCampoDados('e', buscasController.lstLivros[index].$e_termoDeRelacao_700)} ${clUtil.getSubCampoDados('f', buscasController.lstLivros[index].$f_dataDaPublicacaoDoTrabalho_700)} ${clUtil.getSubCampoDados('g', buscasController.lstLivros[index].$g_informacoesAdicionais_700)} ${clUtil.getSubCampoDados('h', buscasController.lstLivros[index].$h_meioDGM)} ${clUtil.getSubCampoDados('i', buscasController.lstLivros[index].$i_informacoesSobreRelacoes)} ${clUtil.getSubCampoDados('j', buscasController.lstLivros[index].$j_atributo)} ${clUtil.getSubCampoDados('k', buscasController.lstLivros[index].$k_subcabecalhos)}  ${clUtil.getSubCampoDados('l', buscasController.lstLivros[index].$l_idiomaDaPublicacao_700)} ${clUtil.getSubCampoDados('m', buscasController.lstLivros[index].$m_instrumentosMusicais)} ${clUtil.getSubCampoDados('n', buscasController.lstLivros[index].$n_numeroDaSecaoDaPublicacao_700)} ${clUtil.getSubCampoDados('o', buscasController.lstLivros[index].$o_arranjoMusical_700)} ${clUtil.getSubCampoDados('p', buscasController.lstLivros[index].$p_nomeDaSecaoDaPublicacao_700)} ${clUtil.getSubCampoDados('q', buscasController.lstLivros[index].$q_formaCompletaDoNome_700)} ${clUtil.getSubCampoDados('r', buscasController.lstLivros[index].$r_escalaMusical_700)} ${clUtil.getSubCampoDados('s', buscasController.lstLivros[index].$s_versao_700)} ${clUtil.getSubCampoDados('t', buscasController.lstLivros[index].$t_tituloDaPublicacao_700)} ${clUtil.getSubCampoDados('u', buscasController.lstLivros[index].$u_afiliacao_700)} ${clUtil.getSubCampoDados('x', buscasController.lstLivros[index].$x_ISSN)} ${clUtil.getSubCampoDados('0', buscasController.lstLivros[index].$0_numeroDeControleDoRegistroDeAutoridade_700)} ${clUtil.getSubCampoDados('3', buscasController.lstLivros[index].$3_materialEspecificado_700)} ${clUtil.getSubCampoDados('4', buscasController.lstLivros[index].$4_relacao_700)} ${clUtil.getSubCampoDados('5', buscasController.lstLivros[index].$5_codigoDaInstituicao_700)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_700)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_700)}',
                        localizacaoEAcessoEletronico_856: '${clUtil.getEtiqueta(buscasController.lstLivros[index].etiqueta_856)} ${clUtil.getIndicadores(buscasController.lstLivros[index].primeiroIndicador_856, buscasController.lstLivros[index].segundoIndicador_856)} ${clUtil.getSubCampoDados('a', buscasController.lstLivros[index].$a_nomeDoServidor)} ${clUtil.getSubCampoDados('b', buscasController.lstLivros[index].$b_numeroDoAcesso)} ${clUtil.getSubCampoDados('c', buscasController.lstLivros[index].$c_informacoesSobreCompactacao)} ${clUtil.getSubCampoDados('d', buscasController.lstLivros[index].$d_caminho)} ${clUtil.getSubCampoDados('f', buscasController.lstLivros[index].$f_nomeDoArquivoEletronico)} ${clUtil.getSubCampoDados('h', buscasController.lstLivros[index].$h_username)} ${clUtil.getSubCampoDados('i', buscasController.lstLivros[index].$i_instrucao)} ${clUtil.getSubCampoDados('j', buscasController.lstLivros[index].$j_bitsPorSegundo)} ${clUtil.getSubCampoDados('k', buscasController.lstLivros[index].$k_password)} ${clUtil.getSubCampoDados('l', buscasController.lstLivros[index].$l_login)} ${clUtil.getSubCampoDados('m', buscasController.lstLivros[index].$m_contatoParaObterAjuda)} ${clUtil.getSubCampoDados('n', buscasController.lstLivros[index].$n_nomeDaLocalizacaoDoServidor)} ${clUtil.getSubCampoDados('o', buscasController.lstLivros[index].$o_sistemaOperativo)} ${clUtil.getSubCampoDados('p', buscasController.lstLivros[index].$p_porta)} ${clUtil.getSubCampoDados('q', buscasController.lstLivros[index].$q_tipoDoFormatoEletronico)} ${clUtil.getSubCampoDados('r', buscasController.lstLivros[index].$r_configuracao)} ${clUtil.getSubCampoDados('s', buscasController.lstLivros[index].$s_tamanhoDoArquivo)} ${clUtil.getSubCampoDados('t', buscasController.lstLivros[index].$t_emulacaoDeTerminal)} ${clUtil.getSubCampoDados('u', buscasController.lstLivros[index].$u_identificadorUniformeDeRecursoURI)} ${clUtil.getSubCampoDados('v', buscasController.lstLivros[index].$v_horarioDeAcesso)} ${clUtil.getSubCampoDados('w', buscasController.lstLivros[index].$w_numeroDeControleDeUmRegistro)} ${clUtil.getSubCampoDados('x', buscasController.lstLivros[index].$x_notaInterna)} ${clUtil.getSubCampoDados('y', buscasController.lstLivros[index].$y_textoDoLink)} ${clUtil.getSubCampoDados('z', buscasController.lstLivros[index].$z_notaDoPublico)} ${clUtil.getSubCampoDados('2', buscasController.lstLivros[index].$2_metodoDeAcesso)} ${clUtil.getSubCampoDados('3', buscasController.lstLivros[index].$3_materialEspecificado_856)} ${clUtil.getSubCampoDados('6', buscasController.lstLivros[index].$6_ligacao_856)} ${clUtil.getSubCampoDados('8', buscasController.lstLivros[index].$8_campoDeLigacaoENumeroDeSequencia_856)}',
                        referencia: ReferenciaWidget(
                          autor: buscasController.lstLivros[index].$a_nomePessoal_100, 
                          titulo: buscasController.lstLivros[index].$a_tituloPrincipal, 
                          subtitulo: buscasController.lstLivros[index].$b_subtitulo, 
                          edicao: buscasController.lstLivros[index].$a_edicao, 
                          local: '${buscasController.lstLivros[index].$a_lugarDePublicacao} ${buscasController.lstLivros[index].$b_nomeDoEditor}', 
                          dataPublicacao: buscasController.lstLivros[index].$c_dataDePublicacao,
                          extensao: buscasController.lstLivros[index].$a_extensao,
                          dimensao: buscasController.lstLivros[index].$c_dimensoes,
                        ),
                      ),
                      reservar: ReservasPesquisaExternaPage(
                        buscasController: buscasController, 
                        index: index, 
                        reservasController: reservasController, 
                        emailController: emailController,
                      ),
                    );
                  },
                ),
                //LISTA DE AUTORIDADES
                CustomListViewWidget(
                  itemCount: buscasController.lstAutoridades.length,
                  itemBuilder: (context, index) {
                    return AutoridadeCardPesquisaExternaWidget(
                      fonteDeCatalogacao: buscasController.lstAutoridades[index].$a_agenciaDeCatalogacaoOriginal,
                      nomePessoal: buscasController.lstAutoridades[index].$a_nomePessoal_100,
                      nomePessoalRemissivaVer: buscasController.lstAutoridades[index].$a_nomePessoal_400,
                      notasGeraisNaoDisponiveis: buscasController.lstAutoridades[index].$a_notaGeralNaoPublica,
                      dadosDeFontesEncontrados: buscasController.lstAutoridades[index].$a_citacaoDeFonte,
                      uri: buscasController.lstAutoridades[index].$u_URI,
                      tabMarcAutoridade: TabCodigoMarcAutoridadeWidget(
                        lider_000: '${clUtil.getEtiqueta(buscasController.lstAutoridades[index].etiqueta_000)} ${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].tamanhoLogicoDoRegistro_00_04, 5)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].statusDoRegistro_05, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].tipoDeRegistro_06, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].posicaoDeCaracteresIndefinida_07_08, 2)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].esquemaDeCodificacaoDeCaracteres_09, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].numeroDeIndicadores_10, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].contagemDeCodigosDeSubcampos_11, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].enderecoDeDadosNaBase_12_16, 5)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].nivelDeCatalogacao_17, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].politicaDePontuacao_18, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].indefinido_19, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].comprimentoDaParteDeComprimentoDeCampo_20, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].comprimentoDaParteDaPosicaoDoCaractereInicial_21, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].comprimentoDaParteDefinidaPelaImplementacao_22, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].indefinido_23, 1)}', 
                        camposDeControle_00x: '${clUtil.getSubCampoDeControle('001', buscasController.lstAutoridades[index].numeroDeControle_001)} ${clUtil.getSubCampoDeControle('\n003', buscasController.lstAutoridades[index].identificadorDoNumeroDeControle_003)} ${clUtil.getSubCampoDeControle('\n005', buscasController.lstAutoridades[index].dataEHoraDaUltimaAtualizacao_005)}', 
                        todosOsMateriais_008: '${clUtil.getEtiqueta(buscasController.lstAutoridades[index].etiqueta_008)} ${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].dataInseridaNoArquivo_00_05, 6)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].subdivisaoGeograficaDiretaOuIndireta_06, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].esquemaDeLatinizacao_07, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].idiomaDoCatalogo_08, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].tipoDeRegistro_09, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].regrasDescritivasDeCatalogacao_10, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].sistemaDeCabecalhoDeAssunto_11, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].tipoDeSerie_12, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].serieNumeradaOuNaoNumerada_13, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].cabecalhoAplicadoEntradaPrincipalOuSecundaria_14, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].cabecalhoAplicadoEntradaDeAssunto_15, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].seriePrincipalESerieSecundaria_16 , 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].tipoDeSubdivisaoDeAssunto_17, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].posicoesDeCaracteresIndifinidas_18_27, 10)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].tipoDeAgenciaGovernamental_28, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].avaliacaoDeReferencias_29, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].posicaoDeCaractereIndefinido_30, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].processoDeAtualizacaoDoRegistro_31, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].nomePessoalNaoDiferenciado_32, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].nivelDeAutorizacao_33, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].posicoesDeCaracteresIndefinidas_34_37, 4)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].registroModificado_38, 1)}${clUtil.getCampoUnicoDados(buscasController.lstAutoridades[index].fonteDeCatalogacao_39, 1)}', 
                        fonteDeCatalogacao_040: '${clUtil.getEtiqueta(buscasController.lstAutoridades[index].etiqueta_040)} ${clUtil.getIndicadores(buscasController.lstAutoridades[index].primeiroIndicador_040, buscasController.lstAutoridades[index].segundoIndicador_040)} ${clUtil.getSubCampoDados('a', buscasController.lstAutoridades[index].$a_agenciaDeCatalogacaoOriginal)} ${clUtil.getSubCampoDados('b', buscasController.lstAutoridades[index].$b_idiomaDaCatalogacao)} ${clUtil.getSubCampoDados('c', buscasController.lstAutoridades[index].$c_agenciaDeTranscricao)} ${clUtil.getSubCampoDados('d', buscasController.lstAutoridades[index].$d_agenciaModificadora)}', 
                        nomePessoal_100: '${clUtil.getEtiqueta(buscasController.lstAutoridades[index].etiqueta_100)} ${clUtil.getIndicadores(buscasController.lstAutoridades[index].primeiroIndicador_100, buscasController.lstAutoridades[index].segundoIndicador_100)} ${clUtil.getSubCampoDados('a', buscasController.lstAutoridades[index].$a_nomePessoal_100)} ${clUtil.getSubCampoDados('d', buscasController.lstAutoridades[index].$d_datasAssociadasAoNome_100)}', 
                        nomePessoalRemissivaVer_400: '${clUtil.getEtiqueta(buscasController.lstAutoridades[index].etiqueta_400)} ${clUtil.getIndicadores(buscasController.lstAutoridades[index].primeiroIndicador_400, buscasController.lstAutoridades[index].segundoIndicador_400)} ${clUtil.getSubCampoDados('a', buscasController.lstAutoridades[index].$a_nomePessoal_400)} ${clUtil.getSubCampoDados('d', buscasController.lstAutoridades[index].$d_datasAssociadasAoNome_400)}', 
                        notaGeralNaoPublica_667: '${clUtil.getEtiqueta(buscasController.lstAutoridades[index].etiqueta_667)} ${clUtil.getIndicadores(buscasController.lstAutoridades[index].primeiroIndicador_667, buscasController.lstAutoridades[index].segundoIndicador_667)} ${clUtil.getSubCampoDados('a', buscasController.lstAutoridades[index].$a_notaGeralNaoPublica)}', 
                        dadosDeFontesEncontrados_670: '${clUtil.getEtiqueta(buscasController.lstAutoridades[index].etiqueta_670)} ${clUtil.getIndicadores(buscasController.lstAutoridades[index].primeiroIndicador_670, buscasController.lstAutoridades[index].segundoIndicador_670)} ${clUtil.getSubCampoDados('a', buscasController.lstAutoridades[index].$a_citacaoDeFonte)} ${clUtil.getSubCampoDados('u', buscasController.lstAutoridades[index].$u_URI)}',
                      ),
                    );
                  },
                ),
                //LISTA DE TESES/TCC/MONOGRAFIAS
                CustomListViewWidget(
                  itemCount: buscasController.lstTeses.length,
                  itemBuilder: (context, index) {
                    return MonografiaTeseDissertacaoCardPesquisaExternaWidget(
                      nomePessoal: buscasController.lstTeses[index].$a_nomePessoal_100, 
                      tituloPrincipal: buscasController.lstTeses[index].$a_tituloPrincipal, 
                      lugarDePublicacao: buscasController.lstTeses[index].$a_lugarDePublicacao, 
                      notaGeral: buscasController.lstTeses[index].$a_notaGeral, 
                      notaDeDissertacaoOuTese: buscasController.lstTeses[index].$a_notaDeDissertacaoOuTese, 
                      nomePessoalSecundario: buscasController.lstTeses[index].$a_nomePessoal_700,
                      uri: buscasController.lstTeses[index].$u_identificadorUniformeDeRecursoURI,
                      tabCodigoMarcMonografiaTeseDissertacao: TabCodigoMarcMonografiaTeseDissertacaoWidget(
                        lider_000:'${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_000)} ${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].tamanhoDoRegistro_00_04, 5)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].statusDoRegistro_05, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].tipoDeRegistro_06, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].nivelBibliografico_07, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].tipodeControle_08, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].esquemaDeCodificacaoDeCaractere_09, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].numeroDeIndicadores_10, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].numeroDeSubcampos_11, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].enderecoDeDados_12_16, 5)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].nivelDeCodificacao_17, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].formaDeCatalogacaoDescritiva_18, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].nivelDeRegistroDeRecurso_19, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].tamanhoDaParteCorrespondenteAoTamanhoDoCampo_20, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].tamanhoDaPosicaoDoCaractereDeInicio_21, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].tamanhoDaParteDefinidaParaImplementacao_22, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].entradaNaoDefinida_23, 1)}',
                        camposDeControle_00x: '${clUtil.getSubCampoDeControle('001', buscasController.lstTeses[index].numeroDeControle_001)} ${clUtil.getSubCampoDeControle('\n003', buscasController.lstTeses[index].codigoAgenciaCatalogadora_003)} ${clUtil.getSubCampoDeControle('\n005', buscasController.lstTeses[index].dataEHoraUltimaAtualizacao_005)}',
                        todosOsMateriais_008: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_008)} ${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].dataDeEntradaDoRegistroNoArquivo_00_05, 6)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].tipodeDataOuStatusDePublicacao_06, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].data1_07_10, 4)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].data2_11_14, 4)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].lugarDePublicacaoProducaoExecucao_15_17, 3)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].ilustracoes_18_21, 4)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].publicoAlvo_22, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].formaDoDocumento_23, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].naturezaDoConteudo_24_27, 4)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].publicacaoGovernamental_28, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].publicacaoDeConferencia_29, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].obraComemorativa_30, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].indice_31, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].indefinido_32, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].formaLiteraria_33, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].biografia_34, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].idiomaDoTextoDoDocumento_35_37, 3)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].registroModificado_38, 1)}${clUtil.getCampoUnicoDados(buscasController.lstTeses[index].fonteDeCatalogacao_39, 1)}',
                        numeroDeClassificacaoDecimalUniversal_080: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_080)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_080, buscasController.lstTeses[index].segundoIndicador_080)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_numeroDeClassificacaoDecimalUniversal)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_numeroDoItem)} ${clUtil.getSubCampoDados('x', buscasController.lstTeses[index].$x_subdivisaoAuxiliarComum)} ${clUtil.getSubCampoDados('0', buscasController.lstTeses[index].$0_numeroDeControleDoRegistroDeAutoridades)} ${clUtil.getSubCampoDados('2', buscasController.lstTeses[index].$2_numeroDeEdicao)} ${clUtil.getSubCampoDados('6', buscasController.lstTeses[index].$6_ligacao_080)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_080)}', 
                        numeroDeChamadaLocal_090: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_090)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_090, buscasController.lstTeses[index].segundoIndicador_090)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_classificacao)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_numeroDeCutter)} ${clUtil.getSubCampoDados('c', buscasController.lstTeses[index].$c_anoDePublicacao)} ${clUtil.getSubCampoDados('d', buscasController.lstTeses[index].$d_tipoDeObra)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_unidadeCatalogadora)}',
                        nomePessoal_100: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_100)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_100, buscasController.lstTeses[index].segundoIndicador_100)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_nomePessoal_100)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_algarismosRomanosQueSeguemPrenome)} ${clUtil.getSubCampoDados('c', buscasController.lstTeses[index].$c_titulosEOutrasPalavrasAssociadasAoNome_100)} ${clUtil.getSubCampoDados('d', buscasController.lstTeses[index].$d_datasAssociadasAoNome_100)} ${clUtil.getSubCampoDados('e', buscasController.lstTeses[index].$e_termoDeRelacao_100)} ${clUtil.getSubCampoDados('f', buscasController.lstTeses[index].$f_dataDaPublicacaoDoTrabalho_100)} ${clUtil.getSubCampoDados('g', buscasController.lstTeses[index].$g_informacoesAdicionais_100)} ${clUtil.getSubCampoDados('j', buscasController.lstTeses[index].$j_atributoQualificador)} ${clUtil.getSubCampoDados('k', buscasController.lstTeses[index].$k_subcabecalho)} ${clUtil.getSubCampoDados('l', buscasController.lstTeses[index].$l_idiomaDaPublicacao_100)} ${clUtil.getSubCampoDados('n', buscasController.lstTeses[index].$n_numeroDaSecaoDaPublicacao_100)} ${clUtil.getSubCampoDados('p', buscasController.lstTeses[index].$p_nomeDaSecaoDaPublicacao_100)} ${clUtil.getSubCampoDados('q', buscasController.lstTeses[index].$q_formaCompletaDoNome_100)} ${clUtil.getSubCampoDados('t', buscasController.lstTeses[index].$t_tituloDaPublicacao_100)} ${clUtil.getSubCampoDados('u', buscasController.lstTeses[index].$u_afiliacao_100)} ${clUtil.getSubCampoDados('0', buscasController.lstTeses[index].$0_numeroDeControleDoRegistroDeAutoridade_100)} ${clUtil.getSubCampoDados('4', buscasController.lstTeses[index].$4_relacao_100)} ${clUtil.getSubCampoDados('6', buscasController.lstTeses[index].$6_ligacao_100)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_100)}', 
                        tituloPrincipal_245: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_245)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_245, buscasController.lstTeses[index].segundoIndicador_245)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_tituloPrincipal)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_subtitulo)} ${clUtil.getSubCampoDados('c', buscasController.lstTeses[index].$c_indicacaoDeResponsabilidade)} ${clUtil.getSubCampoDados('f', buscasController.lstTeses[index].$f_datasDeAbrangencia)} ${clUtil.getSubCampoDados('g', buscasController.lstTeses[index].$g_conjuntoDeDatas)} ${clUtil.getSubCampoDados('h', buscasController.lstTeses[index].$h_meioDGM_245)} ${clUtil.getSubCampoDados('k', buscasController.lstTeses[index].$k_formaDoMaterial)} ${clUtil.getSubCampoDados('n', buscasController.lstTeses[index].$n_numeroDaSecaoDaPublicacao_245)} ${clUtil.getSubCampoDados('p', buscasController.lstTeses[index].$p_nomeDaSecaoDaPublicacao_245)} ${clUtil.getSubCampoDados('s', buscasController.lstTeses[index].$s_versao_245)} ${clUtil.getSubCampoDados('6', buscasController.lstTeses[index].$6_ligacao_245)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_245)}', 
                        imprenta_260: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_260)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_260, buscasController.lstTeses[index].segundoIndicador_260)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_lugarDePublicacao)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_nomeDoEditor)} ${clUtil.getSubCampoDados('c', buscasController.lstTeses[index].$c_dataDePublicacao)} ${clUtil.getSubCampoDados('e', buscasController.lstTeses[index].$e_lugarDeFabricacao)} ${clUtil.getSubCampoDados('f', buscasController.lstTeses[index].$f_nomeDoFabricante)} ${clUtil.getSubCampoDados('g', buscasController.lstTeses[index].$g_dataDeFabricacao)} ${clUtil.getSubCampoDados('3', buscasController.lstTeses[index].$3_materialEspecificado_260)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_260)}',
                        descricaoFisica_300: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_300)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_300, buscasController.lstTeses[index].segundoIndicador_300)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_extensao)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_detalhesFisicosAdicionais)} ${clUtil.getSubCampoDados('c', buscasController.lstTeses[index].$c_dimensoes)} ${clUtil.getSubCampoDados('e', buscasController.lstTeses[index].$e_materialAdicional)} ${clUtil.getSubCampoDados('f', buscasController.lstTeses[index].$f_tipoDeUnidade)} ${clUtil.getSubCampoDados('g', buscasController.lstTeses[index].$g_tamanhoDaUnidade)} ${clUtil.getSubCampoDados('3', buscasController.lstTeses[index].$3_materialEspecificado_300)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_300)}',
                        notaGeral_500: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_500)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_500, buscasController.lstTeses[index].segundoIndicador_500)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_notaGeral)} ${clUtil.getSubCampoDados('3', buscasController.lstTeses[index].$3_materialEspecificado_500)} ${clUtil.getSubCampoDados('5', buscasController.lstTeses[index].$5_codigoDaInstituicao_500)} ${clUtil.getSubCampoDados('6', buscasController.lstTeses[index].$6_ligacao_500)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_500)}',
                        notaDeDissertacaoOuTese_502: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_502)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_502, buscasController.lstTeses[index].segundoIndicador_502)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_notaDeDissertacaoOuTese)} ${clUtil.getSubCampoDados('6', buscasController.lstTeses[index].$6_ligacao_502)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_502)}',
                        notaDeBibliografia_504: buscasController.lstTeses[index].$a_notaDeBibliografia.isEmpty ? '' : '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_504)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_504, buscasController.lstTeses[index].segundoIndicador_504)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_notaDeBibliografia)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_numeroDeReferencias)} ${clUtil.getSubCampoDados('6', buscasController.lstTeses[index].$6_ligacao_504)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_504)}',
                        notaDeResumo_520: buscasController.lstTeses[index].$a_notaDeResumo.isEmpty ? '' : '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_520)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_520, buscasController.lstTeses[index].segundoIndicador_520)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_notaDeResumo)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_expansaoDaNotaDeResumo)} ${clUtil.getSubCampoDados('c', buscasController.lstTeses[index].$c_agenciaDepositaria)} ${clUtil.getSubCampoDados('u', buscasController.lstTeses[index].$u_URI_520)} ${clUtil.getSubCampoDados('2', buscasController.lstTeses[index].$2_fonte_520)} ${clUtil.getSubCampoDados('3', buscasController.lstTeses[index].$3_materialEspecificado_520)} ${clUtil.getSubCampoDados('6', buscasController.lstTeses[index].$6_ligacao_520)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_520)}',
                        topico_650: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_650)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_650, buscasController.lstTeses[index].segundoIndicador_650)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_cabecalhoTopicoOuNomeGeografico)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_cabecalhoTopicoSeguindoNomeGeografico)} ${clUtil.getSubCampoDados('c', buscasController.lstTeses[index].$c_localDoEvento)} ${clUtil.getSubCampoDados('d', buscasController.lstTeses[index].$d_dataDeRealizacaoDoEvento)} ${clUtil.getSubCampoDados('e', buscasController.lstTeses[index].$e_termoDeRelacao_650)} ${clUtil.getSubCampoDados('g', buscasController.lstTeses[index].$g_informacoesAdicionais_650)} ${clUtil.getSubCampoDados('v', buscasController.lstTeses[index].$v_subdivisaoDeForma_650)} ${clUtil.getSubCampoDados('x', buscasController.lstTeses[index].$x_subdivisaoGeral_650)} ${clUtil.getSubCampoDados('y', buscasController.lstTeses[index].$y_subdivisaoCronologica_650)} ${clUtil.getSubCampoDados('z', buscasController.lstTeses[index].$z_subdivisaoGeografica_650)} ${clUtil.getSubCampoDados('0', buscasController.lstTeses[index].$0_numeroDeControleDoRegistroDeAutoridade_650)} ${clUtil.getSubCampoDados('2', buscasController.lstTeses[index].$2_fonteDoCabecalhoOuTermo_650)} ${clUtil.getSubCampoDados('3', buscasController.lstTeses[index].$3_materialEspecificado_650)} ${clUtil.getSubCampoDados('4', buscasController.lstTeses[index].$4_relacao_650)} ${clUtil.getSubCampoDados('6', buscasController.lstTeses[index].$6_ligacao_650)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_650)}',
                        nomePessoalSecundario_700: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_700)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_700, buscasController.lstTeses[index].segundoIndicador_700)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_nomePessoal_700)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_algarismosRomanosQueSeguemOPrenome)} ${clUtil.getSubCampoDados('c', buscasController.lstTeses[index].$c_titulosEOutrasPalavrasAssociadasAoNome_700)} ${clUtil.getSubCampoDados('d', buscasController.lstTeses[index].$d_datasAssociadasAoNome_700)} ${clUtil.getSubCampoDados('e', buscasController.lstTeses[index].$e_termoDeRelacao_700)} ${clUtil.getSubCampoDados('f', buscasController.lstTeses[index].$f_dataDaPublicacaoDoTrabalho_700)} ${clUtil.getSubCampoDados('g', buscasController.lstTeses[index].$g_informacoesAdicionais_700)} ${clUtil.getSubCampoDados('h', buscasController.lstTeses[index].$h_meioDGM)} ${clUtil.getSubCampoDados('i', buscasController.lstTeses[index].$i_informacoesSobreRelacoes_700)} ${clUtil.getSubCampoDados('j', buscasController.lstTeses[index].$j_atributo)} ${clUtil.getSubCampoDados('k', buscasController.lstTeses[index].$k_subcabecalhos)}  ${clUtil.getSubCampoDados('l', buscasController.lstTeses[index].$l_idiomaDaPublicacao_700)} ${clUtil.getSubCampoDados('m', buscasController.lstTeses[index].$m_instrumentosMusicais_700)} ${clUtil.getSubCampoDados('n', buscasController.lstTeses[index].$n_numeroDaSecaoDaPublicacao_700)} ${clUtil.getSubCampoDados('o', buscasController.lstTeses[index].$o_arranjoMusical_700)} ${clUtil.getSubCampoDados('p', buscasController.lstTeses[index].$p_nomeDaSecaoDaPublicacao_700)} ${clUtil.getSubCampoDados('q', buscasController.lstTeses[index].$q_formaCompletaDoNome_700)} ${clUtil.getSubCampoDados('r', buscasController.lstTeses[index].$r_escalaMusical_700)} ${clUtil.getSubCampoDados('s', buscasController.lstTeses[index].$s_versao_700)} ${clUtil.getSubCampoDados('t', buscasController.lstTeses[index].$t_tituloDaPublicacao_700)} ${clUtil.getSubCampoDados('u', buscasController.lstTeses[index].$u_afiliacao_700)} ${clUtil.getSubCampoDados('x', buscasController.lstTeses[index].$x_ISSN_700)} ${clUtil.getSubCampoDados('0', buscasController.lstTeses[index].$0_numeroDeControleDoRegistroDeAutoridade_700)} ${clUtil.getSubCampoDados('3', buscasController.lstTeses[index].$3_materialEspecificado_700)} ${clUtil.getSubCampoDados('4', buscasController.lstTeses[index].$4_relacao_700)} ${clUtil.getSubCampoDados('5', buscasController.lstTeses[index].$5_codigoDaInstituicao_700)} ${clUtil.getSubCampoDados('6', buscasController.lstTeses[index].$6_ligacao_700)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_700)}', 
                        localizacaoEAcessoEletronico_856: '${clUtil.getEtiqueta(buscasController.lstTeses[index].etiqueta_856)} ${clUtil.getIndicadores(buscasController.lstTeses[index].primeiroIndicador_856, buscasController.lstTeses[index].segundoIndicador_856)} ${clUtil.getSubCampoDados('a', buscasController.lstTeses[index].$a_nomeDoServidor)} ${clUtil.getSubCampoDados('b', buscasController.lstTeses[index].$b_numeroDoAcesso)} ${clUtil.getSubCampoDados('c', buscasController.lstTeses[index].$c_informacoesSobreCompactacao)} ${clUtil.getSubCampoDados('d', buscasController.lstTeses[index].$d_caminho)} ${clUtil.getSubCampoDados('f', buscasController.lstTeses[index].$f_nomeDoArquivoEletronico)} ${clUtil.getSubCampoDados('h', buscasController.lstTeses[index].$h_username)} ${clUtil.getSubCampoDados('i', buscasController.lstTeses[index].$i_instrucao)} ${clUtil.getSubCampoDados('j', buscasController.lstTeses[index].$j_bitsPorSegundo)} ${clUtil.getSubCampoDados('k', buscasController.lstTeses[index].$k_password)} ${clUtil.getSubCampoDados('l', buscasController.lstTeses[index].$l_login)} ${clUtil.getSubCampoDados('m', buscasController.lstTeses[index].$m_contatoParaObterAjuda)} ${clUtil.getSubCampoDados('n', buscasController.lstTeses[index].$n_nomeDaLocalizacaoDoServidor)} ${clUtil.getSubCampoDados('o', buscasController.lstTeses[index].$o_sistemaOperativo)} ${clUtil.getSubCampoDados('p', buscasController.lstTeses[index].$p_porta)} ${clUtil.getSubCampoDados('q', buscasController.lstTeses[index].$q_tipoDoFormatoEletronico)} ${clUtil.getSubCampoDados('r', buscasController.lstTeses[index].$r_configuracao)} ${clUtil.getSubCampoDados('s', buscasController.lstTeses[index].$s_tamanhoDoArquivo)} ${clUtil.getSubCampoDados('t', buscasController.lstTeses[index].$t_emulacaoDeTerminal)} ${clUtil.getSubCampoDados('u', buscasController.lstTeses[index].$u_identificadorUniformeDeRecursoURI)} ${clUtil.getSubCampoDados('v', buscasController.lstTeses[index].$v_horarioDeAcesso)} ${clUtil.getSubCampoDados('w', buscasController.lstTeses[index].$w_numeroDeControleDeUmRegistro)} ${clUtil.getSubCampoDados('x', buscasController.lstTeses[index].$x_notaInterna)} ${clUtil.getSubCampoDados('y', buscasController.lstTeses[index].$y_textoDoLink)} ${clUtil.getSubCampoDados('z', buscasController.lstTeses[index].$z_notaDoPublico)} ${clUtil.getSubCampoDados('2', buscasController.lstTeses[index].$2_metodoDeAcesso)} ${clUtil.getSubCampoDados('3', buscasController.lstTeses[index].$3_materialEspecificado_856)} ${clUtil.getSubCampoDados('6', buscasController.lstTeses[index].$6_ligacao_856)} ${clUtil.getSubCampoDados('8', buscasController.lstTeses[index].$8_campoDeLigacaoENumeroDeSequencia_856)}',
                        referencia: ReferenciaWidget(
                          autor: buscasController.lstTeses[index].$a_nomePessoal_100, 
                          titulo: buscasController.lstTeses[index].$a_tituloPrincipal, 
                          subtitulo: buscasController.lstTeses[index].$b_subtitulo, 
                          edicao: "", 
                          local: '${buscasController.lstTeses[index].$a_lugarDePublicacao} ${buscasController.lstTeses[index].$b_nomeDoEditor}', 
                          dataPublicacao: buscasController.lstTeses[index].$c_dataDePublicacao,
                          extensao: buscasController.lstTeses[index].$a_extensao,
                          dimensao: buscasController.lstTeses[index].$c_dimensoes,
                        ),
                      ),
                    );
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
